version: "3.7"

services:
  db:
    image: "postgres:latest"
    container_name: postgres_theatre
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    image: liquidopportunity/theatre
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
        sh -c "python3 manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db:
    driver: local
